services:
  firefox:
    image: jlesage/firefox
    environment:
      - TZ=America/Sao_Paulo
      - DISPLAY_WIDTH=1024
      - DISPLAY_HEIGHT=768
      - VNC_PASSWORD=mypassword
    ports:
      - "5800:5800"
      - "5900:5900"
    volumes:
      - /mnt/appdata/firefox:/config:rw
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - swarm-net

networks:
  swarm-net:
    external: true